### ISSUE TITLE
No rights to access git causes wait-for-repo to retry constantly

### ISSUE THREAD

**Issue by redvox** [flosell/lambdacd#33] opened 2015-07-10 11:24 UTC
I had the problem that the lambdacd user had no rights to access git,
which causes the pipeline to set our git master on fire.

Best regards,
Jens

**Comment by flosell** [comment] 2015-07-11 15:24
Hi Jens, 

I couldn't really reproduce this on my machine, could you give me some pointers? Are you seeing the `wait-for-git` step fail and being retried immediately or does the step stay in waiting state and is just polling very frequently? I added some logging when the polling happens. 

What I did find though is that  `wait-for-git` was very aggresive in general, polling every second. 
4f2e3d7a changes this and makes polling frequency configurable. Maybe also play around with this, you might always have had too much load on your git server due to this and just noticed when investigating your access issues

**Comment by flosell** [comment] 2015-07-12 19:04
Above changes are now released, give version 0.4.2 a try

**Comment by flosell** [comment] 2015-07-24 19:05
closing this unless this reappears and is reproducible

**Closed by flosell** 2015-07-24 19:05 UTC
